name: article_football
channels:
  - conda-forge
dependencies:
  - python==3.7.2
  - pandas==0.25.3
  - lxml==4.6.3
  - matplotlib==3.1.2
  - scikit-learn==0.21.3
  - flask==1.1.1
  - tweepy==3.8.0
  - textblob==0.15.3
  - beautifulsoup4==4.9.3
  - seaborn==0.11.1
